name: Deploy to AWS Lambda
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.4.2

      - name: Provide Execute Permission
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew clean shadowJar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update Function Code
        run: |
          aws lambda update-function-code \
          --function-name clash-guide-function \
          --zip-file fileb://build/libs/clash-guide-api-0.0.1-all.jar
